### ISSUE TITLE
sftp timeout

### ISSUE THREAD

**Issue by codyace** [grev-uv/hpg-methyl#1]
sftp anonymous@clariano.uv.es:/datasets/Homo_sapiens.GRCh37.68.dna.fa genome/
ssh: connect to host clariano.uv.es port 22: Connection timed out
Couldn't read packet: Connection reset by peer

**Comment by cegonse** [comment]
Hello @codyace ,

You can use _ensembl!_ as an alternate repository for genome FASTA files. Check this FTP which contains the human GRCh37 FASTA chromosomes.

[ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/](ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/)

[ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.toplevel.fa.gz](ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.toplevel.fa.gz)
